name: build-and-test

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PipelineEnvironment: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore tests
        run: dotnet restore test/Soenneker.Reflection.Cache.Tests/Soenneker.Reflection.Cache.Tests.csproj --verbosity minimal

      - name: Build tests
        run: dotnet build test/Soenneker.Reflection.Cache.Tests/Soenneker.Reflection.Cache.Tests.csproj --configuration Release --no-restore --verbosity minimal

      - name: Test
        run: dotnet test test/Soenneker.Reflection.Cache.Tests/Soenneker.Reflection.Cache.Tests.csproj --configuration Release --no-build --no-restore --verbosity minimal

      - name: Pack
        run: dotnet pack src/Soenneker.Reflection.Cache/Soenneker.Reflection.Cache.csproj --configuration Release --no-build --no-restore --output . --verbosity minimal
